#! /usr/bin/perl -w

use strict;
use FindBin;
use lib "$FindBin::Bin/lib";

use Quick_SSL;

=begin comment
This script prints the expiry dates of SSL certificates of websites listed in a text file.
The URLs in the list file that is passed as an argument are expected to be in this format:

www.example.com
www.anotherexample.co.uk
www.yetanotherexample.it 

Please note that the URLs should not contain the scheme part (e.g. http://). 

Example usage:
$./check_ssl_cert_expiry url_list.txt

=end comment

=cut


# We expect a file containing a list of URLs to be passed as an argument.
# The script quits if the list is not specified.
my $num_args = $#ARGV + 1;
if ($num_args != 1) {
    print "\nYou need to specify a file containing a list of URLs to check.\n For example:\n\$check_ssl_cert_expiry url_list.txt\nTerminating...\n";
    exit;
}

my $filename = $ARGV[0]; 

my $c = Quick_SSL->new();
$c->print_sorted_expiry_dates($filename);
