#! /usr/bin/perl -w


use strict;
use Quick_SSL;

# We expect a list of URLs to be passed as an argument.
# The script quits if the list is not specified.
my $num_args = $#ARGV + 1;
if ($num_args != 1) {
    print "\nYou need to specify a file containing a list of URLs to check.\n For example:\n\$check_ssl_cert_expiry url_list.txt\nTerminating...";
    exit;
}

my $filename = $ARGV[0]; 

my $c = Quick_SSL->new();
$c->print_sorted_expiry_dates($filename);
